pipeline {

    agent any

    tools {
        maven 'mymaven'
    }

    environment {
        NAME = "Milos"
    }

    parameters {
        string defaultValue: 'Diklic', name: 'LASTNAME'
    }

    stages {
        stage('build') {
            steps {
                echo "JA SAM $NAME ${params.LASTNAME}"
            }
        }

        stage('test') {
            parallel {
                stage('testA') {
                    steps {
                        echo "Test A"
                    }
                }

                stage('testB') {
                    steps {
                        echo "Test B"
                    }
                }
            }
        }
    }
}