pipeline {
    
    agents none

    stages {
        stage('build') {
            steps {
                echo "this is build stage"
            }
        }

        stage('test') {
            steps {
                echo "this is test stage"
            }
        }

        stage('deply') {
            steps {
                echo "this is deploy stage"
            }
        }
    }
}